### ISSUE TITLE
index.html rewards animation

### ISSUE THREAD

**Issue by oguzbakir** [ACMHacettepeDevelopers/Acm-Huprog-Site-2019#1]
While rewards animation updating, it shifts content on below.

**Comment by emrekosen** [comment]
Thanks for feedback! We are working on it.(This is not a bot.)

**Comment by batuberksahin** [comment]
Done. [#commit](https://github.com/ACMHacettepeDevelopers/Acm-Huprog-Site-2019/commit/85a74c1fbe2fc26b7de213ff8c17bcf5142b0cd9#diff-09234fa481e0f19df8e1d871db659d18R58)
